export { ArrowIcon } from './arrow'
export { CloseIcon } from './close'
export { InstallIcon } from './install'
export { MenuIcon } from './menu'
export { SearchIcon } from './search'
export { TriangleFillIcon } from './triangle-fill'
export { TriangleOutlineIcon } from './triangle-outline'
